// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHtjXzzaJcnTuLCbv_JhZMqYGLaced6cY',
    appId: '1:338177179297:web:b41ac423d7b097a9fafae0',
    messagingSenderId: '338177179297',
    projectId: 'beaming-edition-234519',
    authDomain: 'beaming-edition-234519.firebaseapp.com',
    storageBucket: 'beaming-edition-234519.appspot.com',
    measurementId: 'G-XJ7FZ55D5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSwsAV9s9yMmgaKAIwgMZpct4TLcJFS6c',
    appId: '1:338177179297:android:118f2b506f754306fafae0',
    messagingSenderId: '338177179297',
    projectId: 'beaming-edition-234519',
    storageBucket: 'beaming-edition-234519.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQOlWI-hf7cuGMtOLV7MnisbiBQe67W7g',
    appId: '1:338177179297:ios:28b2cb0c6173eb45fafae0',
    messagingSenderId: '338177179297',
    projectId: 'beaming-edition-234519',
    storageBucket: 'beaming-edition-234519.appspot.com',
    iosClientId: '338177179297-btbuko54gkq8fe8rtr7ktljdmokcgnuo.apps.googleusercontent.com',
    iosBundleId: 'com.example.precios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQOlWI-hf7cuGMtOLV7MnisbiBQe67W7g',
    appId: '1:338177179297:ios:28b2cb0c6173eb45fafae0',
    messagingSenderId: '338177179297',
    projectId: 'beaming-edition-234519',
    storageBucket: 'beaming-edition-234519.appspot.com',
    iosClientId: '338177179297-btbuko54gkq8fe8rtr7ktljdmokcgnuo.apps.googleusercontent.com',
    iosBundleId: 'com.example.precios',
  );
}
